apiVersion: v1
kind: ServiceAccount
metadata:
  name: candy-svc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: candy-service-config
data:
  candy.cfg: |-
    candy.peppermint.power=100000000
    candy.nougat-armor.strength=10
---
apiVersion: v1
kind: Secret
metadata:
  name: db-password
type: Opaque
stringData:
  password: Kub3rn3t3sRul3s!
---
apiVersion: v1
kind: Pod
metadata:
  name: candy-service
spec:
  serviceAccountName: candy-svc
  containers:
    - name: myapp
      image: linuxacademycontent/candy-service:1
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: password
      envFrom:
        - secretRef:
            name: db-password
      volumeMounts:
          - name: config-volume
            mountPath: /etc/candy-service
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
  volumes:
  - name: config-volume
    configMap:
      name: candy-service-config
